### Message synchronization
# max time difference between images
max_time_diff: 0.05



### Verbosity
# verbose: Whether to enable verbose output
verbose: true



### Point cloud segmentation
# visualize: Whether to visualize the segmentation process
visualize: false
# sigma_s: Spatial standard deviation for smoothness weight calculation
sigma_s: 5.0
# sigma_r: Range standard deviation for smoothness weight calculation
sigma_r: 0.005
# max_change_factor: Maximum allowed change factor between points
max_change_factor: 0.05
# smoothing_size: Size of the Gaussian kernel for smoothing
smoothing_size: 10
# inliers_ratio: Ratio of inliers required for segmentation
inliers_ratio: 0.05
# angular_th: Maximum allowed angle between normals
angular_th: 0.1
# distance_th: Maximum allowed distance between points
distance_th: 0.03



### Parameters for RGB image processing
# fx: Focal length of the camera along the x-axis
fx: 533.705105
# fy: Focal length of the camera along the y-axis
fy: 533.669422
# cx: X-coordinate of the principal point/optical center of the camera in pixels
cx: 326.790376
# cy: Y-coordinate of the principal point/optical center of the camera in pixels
cy: 247.069550
# D: 5-component distortion vector
D: [0.000274, -0.041651, -0.002869, -0.001532, 0.000000]
# checkerboardWidth: Number of inner corners of the checkerboard(s) used for RGB calibration in the first dimension
checkerboardWidth: 7
# checkerboardHeight: Number of inner corners of the checkerboard(s) used for RGB calibration in the second dimension
checkerboardHeight: 4
# squareSize: Side length of checkerboard squares in meters
squareSize: 0.03



### Parameters for calibration setting
# max_angle: Maximum angle for calibration
max_angle: 60.0
# max_distance: Maximum distance for calibration
max_distance: 2.0
# calib_strategy: Calibration strategy ('star' or 'redundant')
calib_strategy: standard
# algorithm: Algorithm selection for calibration
algorithm: lm_robust

# error_analysis: runs the calibration 25 times using a random set of `lim_correspondences` for every calibration
error_analysis: false
# lim_correspondences: Limits the max correspondences number to be considered for calibration (for error convergence analysis), set to big number if should not be limited
lim_correspondences: 1000


#   Available algorithm options:
#   - 'std'
#   - 'lm': Levenberg-Marquardt
#   - 'lm_robust': Levenberg-Marquardt (robust version)
#   - 'gn': Gauss-Newton
#   - 'gn_robust': Gauss-Newton (robust version)



### Sensor information 
# Sensor naming convention:
# Use the following naming convention:
# "ti" : initial translation of sensor i wrt the sensor 0 in m
# "ri" : initial rotation of sensor i wrt the sensor 0 in degrees (yaw/pitch/roll)
# "topic_i"   : topic of sensor i
# "msgtype_i" : message type the topic of sensor i publishes to
#
# When using different sensor types: Put all PointCloud2 sensor(s) before 
# listing RGB sensor(s)!

# num_sensors: Number of sensors
num_sensors: 2

t0: [0.0, 0.0, 0.0]
r0: [0.0, 0.0, 0.0]
topic_0: "/camera1/color/image_raw"
msgtype_0: "Image"


#t1: [0.42, 0.52, 0.0]
#r1: [0.0, -45.0, 0.0]
t1: [1.0, -0.7, 0]
r1: [0.0, -45, 0.0]
topic_1: "/camera2/color/image_raw"
msgtype_1: "Image"

#t2: [0.20, 0.0, -0.10]
#r2: [12.0, 0.0, 0.0]
#topic_2: "/camera2/color/image_raw"
#msgtype_2: "Image"
2,90 y 1.30 x 0.78 y  45 y y -30 en x